// Generated by CoffeeScript 1.7.1
jQuery(function($) {
  var animateBg, last_percent;
  last_percent = 0;
  animateBg = function() {
    var blur, filterStr, percent;
    percent = $(this).scrollTop() / $(window).height() * 100;
    percent = Math.max(0, Math.min(100, percent));
    percent = Math.floor(percent / 5) * 5;
    if (percent === last_percent) {
      return false;
    }
    if (!navigator.userAgent.match(/iPhone|iPod|iPad/)) {
      blur = Math.floor(20 * percent / 100);
      filterStr = "blur(" + blur + "px)";
      $('#bg').css({
        fliter: filterStr,
        webkitFilter: filterStr,
        mozFilter: filterStr,
        msFilter: filterStr
      });
    }
    $('#bg').css({
      opacity: 1 - percent * 0.7 / 100
    });
    $('.down').css({
      opacity: Math.max(0, 1 - percent * 3 / 100)
    });
    return last_percent = percent;
  };
  if ($('body.single').length === 0 && $('body.error404').length === 0) {
    $('header, .headerBox').height($(window).height());
    $('.down').on('click', function() {
      return $('html,body').animate({
        scrollTop: $('.container').offset().top
      }, {
        duration: 700,
        easing: 'swing'
      });
    });
    $(window).scroll(function() {
      return animateBg();
    });
    animateBg();
  }
  $('.about').on('click', function(e) {
    $('.aboutBox').show();
    return e.preventDefault();
  });
  $('.aboutInner').on('click', function(e) {
    return e.stopPropagation();
  });
  $('.aboutBox, .aboutInner .close').on('click', function(e) {
    $('.aboutBox').fadeOut(150);
    return e.preventDefault();
  });
  return $('.pageTop').on('click', function(e) {
    $('html,body').scrollTop(0);
    return e.preventDefault();
  });
});

//# sourceMappingURL=script.map
